### ISSUE TITLE
Does this still work ?

### ISSUE THREAD

**Issue by IvRRimum** [sebi/googl-php#6]
I required the class at the top of my PHP file, created object

$url = new Googl(MY_APY_KEY);

But when i call

$url->shorten($post_url);

It returns NULL

**Comment by IvRRimum** [comment]
Also Curls are enabled, and i ran you'r tests.php file, It fails at first test.

**Comment by sebi** [comment]
It seems like Google changed the API. It now requires authorization for every request, which breaks our test suite. 

You now must authorize against the API using either OAuth (not supported by this library) or by using the application key (supported, just pass your API key in the constructor like mentioned in the docs of this library).

Thanks for the heads up!

**Comment by sebi** [comment]
I updated the docs accordingly. https://github.com/sebi/googl-php/commit/b04db78e26eda986b7feee94b97e768f92a93c7e
